version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Installing project dependencies
                command: npm install
            - run:
                name: Run unit tests
                command: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test